Il est possible, comme pour le RFXcom, EnOcean, Edisio, SMS, MySensor... de déporter l'antenne Z-Wave (indépendamment du type de serveur Z-Wave utilisé, vous pouvez même mixer).

==== Pourquoi le déporter ?

Cela permet déjà de réduire la charge sur le Jeedom central, en délégant une partie de la gestion Z-Wave à l'esclave. Cela peut aussi vous permettre de mettre le coeur de Jeedom à un endroit (garage par exemple) et l'antenne Z-Wave dans la maison pour mieux couvrir la zone.

Dernier intérêt, il est possible d'avoir jusqu'à 3 antennes Z-Wave, ce qui vous permet de couvrir différentes zones ou de séparer des capteurs pour plus de sécurité, car en cas de défaillance d'un contrôleur tous les modules ne deviennent pas inaccessibles.

==== Comment le déporter ?

Déporter le Z-Wave est assez simple, il faut sur le système qui servira d'esclave : 

* installer jeedom (non obligatoire pour le Z-Way server) (si vous partez d'un jeedom pré-installé ou d'une image officielle avec un razberry cette étape n'est pas nécessaire)
* installer votre serveur Z-Wave (si vous partez d'un jeedom pré-installé ou d'une image officielle avec un razberry cette étape n'est pas nécessaire)
* mettre le jeedom en esclave (si vous l'avez installé bien sûr, pour rappel c'est obligatoire avec le serveur Z-Wave Open-Zwave)
* sur le maître il vous faut juste indiquer l'ip de l'esclave

[icon="../images/plugin/tip.png"]
[TIP]
Si vous partez d'un jeedom où il y a le razberry et jeedom maître sur la même carte, pour arriver sur un jeedom maître sans razberry et un jeedom esclave avec le razberry, vous pouvez suivre la démarche plus haut. Puis dans l'administration du serveur Z-Wave faire un soigner le réseau Z-Wave, cela vous permettra de récupérer tous les modules. Attention quand même dans ce cas à bien remplacer sur le maître l'IP 127.0.0.1 par celle de l'esclave.
