Il est possible, comme pour le RFXcom, EnOcean, Edisio, SMS, MySensor... de déporter l'antenne Zwave (independement du type de serveur zwave utilisé, vous pouvez meme mixer).

==== Pourquoi le deporter ?

Cela permet deja de reduire la charge sur le Jeedom centrale, en delegant une partie de la gestion zwave à l'esclave, cela peut aussi vous permettre de mettre le coeur de Jeedom a un endroit (garage par exemple) et l'antenne zwave dans la maison pour mieux couvrir la zone.

Derniere interet il est possible d'avoir jusqu'a 3 antennes zwave, cela vous permet donc de couvrir differente zone ou de separer des capteur pour plus de securité en cas de defaillance d'un controleur tous les modules ne deviennent pas inaccessible

==== Comment le deporter ?

Deporter le zwave est assez simple, il faut sur le systeme qui servira d'esclave : 

* installer jeedom (non obligatoire pour le zway server)
* installer votre serveur zwave (si vous partez d'un jeedom preinstallé ou d'une image officiel et avec un razberry ces étapes ne sont pas necessaire)
* mettre le jeedom en esclave (si vous l'avez installé bien sur, pour rappel c'est obligatoire avec le serveur zwave openzwave)
* sur le maitre il vous faut juste indiquer l'ip de l'esclave

[icon="../images/plugin/tip.png"]
[TIP]
Si vous partez d'un jeedom ou il y a le razberry et jeedom maitre sur la meme carte pour arriver sur un jeedom maitre sans razberry et un jeedom esclave avec le razberry, vous pouvez suivre la demarche plus haut puis dans l'administration du serveur zwave faire un soigner le reseaux zwave, cela vous permettra de recuperer tous les modules. Attention quand meme dans ce cas à bien remplacer sur le mettre l'IP 127.0.0.1 par celle de l'esclave